### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by idleberg** [konapun/atom-theme-manager#1]
[Enter steps to reproduce below:]
1. Open command-palette
2. Select _Theme Manager: Change Theme_

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.9.5
**Thrown From**: [atom-theme-manager](https://github.com/konapun/atom-theme-manager) package, v0.0.3
### Stack Trace

Uncaught TypeError: Cannot convert undefined or null to object

```
At /Users/me/.atom/packages/atom-theme-manager/lib/theme-manager.js:38

TypeError: Cannot convert undefined or null to object
    at Object.getThemeNames (/Users/me/.atom/packages/atom-theme-manager/lib/theme-manager.js:38:19)
    at ChangeThemeView.changeTheme (/Users/me/.atom/packages/atom-theme-manager/lib/change-theme-view.js:20:37)
    at atom-workspace.themeManagerChangeTheme (/Users/me/.atom/packages/atom-theme-manager/lib/index.js:29:30)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -0:03.1.0 command-palette:toggle (div.package-detail.panels-item)
     -0:00.3.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:00.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.1.0 theme-manager:change-theme (div.package-detail.panels-item)
```
### Config

``` json
{
  "core": {
    "automaticallyUpdate": false,
    "disabledPackages": [
      "wrap-guide",
      "autocomplete-plus",
      "auto-update-packages",
      "build-makensis-wine",
      "minimap-highlight-selected",
      "build-nsl"
    ],
    "themes": [
      "one-dark-ui",
      "hopscotch"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
anderson-dark-syntax, v0.1.0 (inactive)
anderson-dark-ui, v0.1.0 (inactive)
atom-material-ui, v1.3.6 (inactive)
atom-theme-manager, v0.0.3 (active)
atomizr, v0.16.4 (inactive)
auto-update-packages, v1.0.1 (inactive)
auto-update-plus, v0.1.3 (active)
badges, v2.2.4 (active)
browse, v1.3.1 (inactive)
build, v0.65.0 (active)
build-bsc, v0.1.4 (active)
build-lsc, v0.2.1 (active)
build-makensis, v0.11.9 (active)
build-makensis-wine, v0.10.9 (inactive)
build-nsl, v0.6.6 (inactive)
build-ozc, v0.1.3 (active)
build-python, v0.2.1 (active)
busy, v0.7.0 (active)
cson, v2.0.1 (active)
edit-local-storage, v0.0.0 (inactive)
file-icons, v1.7.19 (active)
flex-tool-bar, v0.11.0 (active)
git-time-machine, v1.5.3 (inactive)
hopscotch, v1.6.1 (active)
icon-fonts, v2.8.4 (active)
keyboard-localization, v1.4.18 (active)
language-applescript, v0.2.2 (inactive)
language-bridlensis, v2.1.1 (inactive)
language-innosetup, v2.0.0 (inactive)
language-innosetup, v2.0.0 (inactive)
language-json-comments, v0.16.3 (active)
language-julia, v0.6.0 (active)
language-livescript, v0.0.3 (active)
language-nlf, v1.1.5 (active)
language-nsis, v5.5.1 (inactive)
language-nsl, v2.1.1 (inactive)
language-ocaml, v1.1.2 (active)
language-restructuredtext, v1.0.0 (active)
language-squirrel, v0.4.3 (active)
latex-completions, v0.3.2 (active)
linter, v1.11.16 (active)
linter-csslint, v1.3.2 (active)
linter-jshint, v3.0.0 (active)
linter-jslint, v10.2.0 (active)
linter-jsonlint, v1.3.0 (active)
linter-php, v1.2.0 (active)
local-storage, v0.1.1 (inactive)
minimap, v4.25.0 (active)
minimap-cursorline, v0.2.0 (active)
minimap-highlight-selected, v4.4.0 (inactive)
minimap-linter, v1.6.0 (active)
minimap-selection, v4.4.0 (active)
multi-cursor, v2.1.3 (inactive)
nsis-ide, v0.7.0 (active)
nsis-plugins, v1.2.1 (active)
open-in-developer-mode, v0.1.0 (inactive)
package-developer-toolbar, v0.8.0 (active)
paraiso-black, v1.0.5 (inactive)
paraiso-dark, v1.3.1 (inactive)
paraiso-dark-tuned, v2.0.6 (inactive)
pretty-json, v1.6.0 (active)
quick-scroll, v2.1.1 (active)
raml, v0.2.0 (active)
script, v3.10.1 (inactive)
set-syntax, v0.3.0 (active)
Stylus, v3.0.0 (active)
symbols-tree-view, v0.13.2 (active)
tool-bar, v1.0.1 (active)
travis-ci-status, v1.3.0 (active)
unicode-input, v0.5.1 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (inactive)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (inactive)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by konapun** [comment]
Thanks for the report. I'll get this fixed in the next release.
